name: CI

on: [push, pull_request]

jobs:
  test-plugin:
    name: Linux x64_64
    runs-on: ubuntu-latest

    env:
      REPODIR: "${{ github.workspace }}"
      APPDIR: "/tmp/AppDir"
      DEPLOY_GTK_VERSION: 3

    steps:
    - uses: actions/checkout@v2

    - name: Setup dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y -qq libgtk-3-0 libgtk-3-dev wget tree

    - name: Download external binairies
      run: |
        wget -qc "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
        wget -qc "https://raw.githubusercontent.com/linuxdeploy/misc-plugins/master/tests/test-plugins.sh"
        echo "LINUXDEPLOY=$(readlink -f linuxdeploy-x86_64.AppImage)" >> $GITHUB_ENV
        chmod +x *.AppImage *.sh

    - name: Run test script
      run: |
        mkdir -pv "$APPDIR/usr/bin"
        ./test-plugins.sh

    - name: Display files inside AppDir
      run: tree "$APPDIR"
